# Generated by Django 4.2.7 on 2024-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermark',
            name='preference_level',
            field=models.IntegerField(default=0),
        ),
    ]
