# Generated by Django 4.2.7 on 2024-12-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_usermark_preference_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='tags',
            field=models.ManyToManyField(related_name='marks', to='marks.tag'),
        ),
    ]
