# Generated by Django 4.2.7 on 2024-12-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_administrator_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mark_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='is_mark_manager',
            field=models.BooleanField(default=True, help_text='Can manage Marks'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='is_tag_manager',
            field=models.BooleanField(default=True, help_text='Can manage Tags'),
        ),
    ]
